// Datos de galerias, openings e imagenes

const TOP_CATEGORIES = [
  { id: "hentai", name: "Galerias hentai", desc: "Manga / hentai + flashcards", icon: "🖼️", active: true },
  { id: "openings", name: "Openings", desc: "Vocabulario de openings de anime", icon: "🎵", active: true }
];

const OPENINGS = [
  { id: "op-dark-seeks-light", name: "Dark seeks light", anime: "Sicario isekai (Ansatsusha)", artist: "ニノミヤユイ", active: true },
  { id: "op-nanatsu-1", name: "熱情のスペクトラム", anime: "Nanatsu no Taizai OP1", artist: "いきものがかり", active: true },
  { id: "op-tsubasa", name: "ツバサ", anime: "Mushoku Tensei (Nanahoshi cover)", artist: "ナナホシ / UNDERGRAPH", active: true }
];

const MAIN_GALLERIES = [
  { id: "1", name: "quintiputas", active: true, subs: [
    { id: "1.1", name: "Proximamente", active: false }, { id: "1.2", name: "Proximamente", active: false },
    { id: "1.3", name: "Proximamente", active: false }, { id: "1.4", name: "Proximamente", active: false },
    { id: "1.5", name: "Proximamente", active: false }
  ]},
  { id: "2", name: "Historias cortas", active: true, subs: [
    { id: "2.1", name: "itsuki playera putona", active: true },
    { id: "2.2", name: "ichika putona sexo de chill", active: true },
    { id: "2.3", name: "Proximamente", active: false }, { id: "2.4", name: "Proximamente", active: false },
    { id: "2.5", name: "Proximamente", active: false }
  ]},
  { id: "3", name: "Galeria 3", active: false, subs: [{ id: "3.1", name: "Proximamente", active: false },{ id: "3.2", name: "Proximamente", active: false },{ id: "3.3", name: "Proximamente", active: false },{ id: "3.4", name: "Proximamente", active: false },{ id: "3.5", name: "Proximamente", active: false }] },
  { id: "4", name: "Galeria 4", active: false, subs: [{ id: "4.1", name: "Proximamente", active: false },{ id: "4.2", name: "Proximamente", active: false },{ id: "4.3", name: "Proximamente", active: false },{ id: "4.4", name: "Proximamente", active: false },{ id: "4.5", name: "Proximamente", active: false }] },
  { id: "5", name: "Galeria 5", active: false, subs: [{ id: "5.1", name: "Proximamente", active: false },{ id: "5.2", name: "Proximamente", active: false },{ id: "5.3", name: "Proximamente", active: false },{ id: "5.4", name: "Proximamente", active: false },{ id: "5.5", name: "Proximamente", active: false }] },
  { id: "6", name: "Galeria 6", active: false, subs: [{ id: "6.1", name: "Proximamente", active: false },{ id: "6.2", name: "Proximamente", active: false },{ id: "6.3", name: "Proximamente", active: false },{ id: "6.4", name: "Proximamente", active: false },{ id: "6.5", name: "Proximamente", active: false }] },
  { id: "7", name: "Galeria 7", active: false, subs: [{ id: "7.1", name: "Proximamente", active: false },{ id: "7.2", name: "Proximamente", active: false },{ id: "7.3", name: "Proximamente", active: false },{ id: "7.4", name: "Proximamente", active: false },{ id: "7.5", name: "Proximamente", active: false }] },
  { id: "8", name: "Galeria 8", active: false, subs: [{ id: "8.1", name: "Proximamente", active: false },{ id: "8.2", name: "Proximamente", active: false },{ id: "8.3", name: "Proximamente", active: false },{ id: "8.4", name: "Proximamente", active: false },{ id: "8.5", name: "Proximamente", active: false }] },
  { id: "9", name: "Galeria 9", active: false, subs: [{ id: "9.1", name: "Proximamente", active: false },{ id: "9.2", name: "Proximamente", active: false },{ id: "9.3", name: "Proximamente", active: false },{ id: "9.4", name: "Proximamente", active: false },{ id: "9.5", name: "Proximamente", active: false }] },
  { id: "10", name: "Galeria 10", active: false, subs: [{ id: "10.1", name: "Proximamente", active: false },{ id: "10.2", name: "Proximamente", active: false },{ id: "10.3", name: "Proximamente", active: false },{ id: "10.4", name: "Proximamente", active: false },{ id: "10.5", name: "Proximamente", active: false }] }
];

const GALLERIES = {
  "2.1": { name: "itsuki playera putona", cover: "", images: ["https://img.ge/i/wmODD63.png", "https://img.ge/i/oo9rL91.png"] },
  "2.2": { name: "ichika putona sexo de chill", cover: "", images: ["https://img.ge/i/6ot6t26.png", "https://img.ge/i/dazsg51.png"] }
};

const FLASHCARDS = {
  "2.1": [
    { word: "見ないで", romaji: "minaite de", meaning: "no mires", distractors: ["no hables", "no toques", "no te vayas"] },
    { word: "正気", romaji: "shoki", meaning: "cuerdo / cordura", distractors: ["loco", "enfermo", "cansado"] },
    { word: "水着", romaji: "mizugi", meaning: "traje de bano", distractors: ["toalla", "sombrero", "gafas"] },
    { word: "忘れて", romaji: "wasurete", meaning: "olvidar (forma te)", distractors: ["recordar", "llevar", "comprar"] },
    { word: "予備", romaji: "yobi", meaning: "de repuesto / reserva", distractors: ["principal", "roto", "nuevo"] },
    { word: "波", romaji: "nami", meaning: "ola", distractors: ["viento", "lluvia", "sol"] },
    { word: "凄かった", romaji: "sugokatta", meaning: "fue increible / genial", distractors: ["fue malo", "fue normal", "fue pequeno"] },
    { word: "隠せ", romaji: "kakuse", meaning: "cubre / esconde", distractors: ["muestra", "abre", "tira"] },
    { word: "前", romaji: "mae", meaning: "frente / delante", distractors: ["atras", "lado", "arriba"] },
    { word: "波が", romaji: "nami ga", meaning: "la ola (sujeto)", distractors: ["el viento", "la arena", "el sol"] },
    { word: "お前", romaji: "omae", meaning: "tu (informal)", distractors: ["yo", "el", "nosotros"] },
    { word: "持って来て", romaji: "motte kite", meaning: "traer (forma te)", distractors: ["llevarse", "dejar", "romper"] }
  ],
  "2.2": [
    { word: "結局", romaji: "kekkyoku", meaning: "al final", distractors: ["al principio", "de repente", "quizas"] },
    { word: "朝まで", romaji: "asa made", meaning: "hasta la manana", distractors: ["hasta la noche", "todo el dia", "un momento"] },
    { word: "しちゃった", romaji: "shichatta", meaning: "lo hicimos", distractors: ["lo dejamos", "lo olvidamos", "lo intentamos"] },
    { word: "どうする", romaji: "do suru", meaning: "que hacemos?", distractors: ["quien eres?", "donde vas?", "cuando es?"] },
    { word: "もう一回", romaji: "mo ikkai", meaning: "una vez mas", distractors: ["la ultima vez", "nunca mas", "dos veces"] },
    { word: "学校", romaji: "gakko", meaning: "escuela", distractors: ["casa", "trabajo", "hospital"] },
    { word: "遅れる", romaji: "okureru", meaning: "llegar tarde", distractors: ["llegar temprano", "salir", "correr"] },
    { word: "一緒に", romaji: "issho ni", meaning: "juntos", distractors: ["solo", "despues", "antes"] },
    { word: "サボる", romaji: "saboru", meaning: "saltarse / faltar", distractors: ["estudiar", "llegar", "aprobar"] },
    { word: "おいで", romaji: "oide", meaning: "ven aqui", distractors: ["vete", "espera", "duerme"] },
    { word: "いい加減に", romaji: "ii kagen ni", meaning: "ya basta", distractors: ["por favor", "de acuerdo", "con cuidado"] },
    { word: "やる気", romaji: "yaruki", meaning: "ganas / motivacion", distractors: ["sueno", "hambre", "miedo"] },
    { word: "満々", romaji: "manman", meaning: "a tope", distractors: ["vacio", "poco", "a medias"] },
    { word: "やめ", romaji: "yame", meaning: "para / deja de", distractors: ["sigue", "empieza", "mira"] },
    { word: "バレたら", romaji: "baretara", meaning: "si nos descubren", distractors: ["si ganamos", "si llueve", "si terminamos"] },
    { word: "あいつら", romaji: "aitsura", meaning: "ellos (informal)", distractors: ["nosotros", "tu", "nadie"] },
    { word: "みんなで", romaji: "minna de", meaning: "todos juntos", distractors: ["solo yo", "de dos", "nadie"] }
  ],
  "op-dark-seeks-light": [
    { word: "不平等", romaji: "fubyodo", meaning: "desigualdad", distractors: ["igualdad", "paz", "libertad"] },
    { word: "生", romaji: "sei", meaning: "vida", distractors: ["muerte", "sueno", "tiempo"] },
    { word: "密かに", romaji: "hisoka ni", meaning: "en secreto", distractors: ["abiertamente", "rapido", "juntos"] },
    { word: "狂乱", romaji: "kyoran", meaning: "frenesi", distractors: ["calma", "silencio", "orden"] },
    { word: "正義", romaji: "seigi", meaning: "justicia", distractors: ["maldad", "mentira", "odio"] },
    { word: "独善", romaji: "dokuzen", meaning: "autocomplacencia", distractors: ["humildad", "bondad", "duda"] },
    { word: "未来", romaji: "mirai", meaning: "futuro", distractors: ["pasado", "presente", "historia"] },
    { word: "名誉", romaji: "meiyo", meaning: "honor", distractors: ["verguenza", "odio", "miedo"] },
    { word: "愛情", romaji: "aijo", meaning: "amor", distractors: ["odio", "indiferencia", "ira"] },
    { word: "生命", romaji: "inochi", meaning: "vida (vital)", distractors: ["muerte", "alma", "cuerpo"] },
    { word: "意味", romaji: "imi", meaning: "significado", distractors: ["ruido", "error", "vacio"] },
    { word: "倫理", romaji: "rinri", meaning: "etica", distractors: ["ley", "juego", "arte"] },
    { word: "理想", romaji: "riso", meaning: "ideal", distractors: ["realidad", "mentira", "sueno"] },
    { word: "幻想", romaji: "genso", meaning: "ilusion", distractors: ["verdad", "hecho", "prueba"] },
    { word: "運命", romaji: "unmei", meaning: "destino", distractors: ["azar", "eleccion", "pasado"] },
    { word: "暗闇", romaji: "kurayami", meaning: "oscuridad", distractors: ["luz", "brillo", "dia"] },
    { word: "殺す", romaji: "korosu", meaning: "matar", distractors: ["salvar", "curar", "proteger"] },
    { word: "痛み", romaji: "itami", meaning: "dolor", distractors: ["placer", "alegria", "calma"] },
    { word: "絶望", romaji: "zetsubo", meaning: "desesperacion", distractors: ["esperanza", "alegria", "paz"] },
    { word: "叫ぶ", romaji: "sakebu", meaning: "gritar", distractors: ["susurrar", "callar", "reír"] }
  ],
  "op-nanatsu-1": [
    { word: "鳴りやまぬ", romaji: "nariyamanu", meaning: "que no cesa", distractors: ["que para", "silencioso", "debil"] },
    { word: "愛", romaji: "ai", meaning: "amor", distractors: ["odio", "miedo", "ira"] },
    { word: "叫ぶ", romaji: "sakebu", meaning: "gritar", distractors: ["susurrar", "callar", "cantar"] },
    { word: "すべて", romaji: "subete", meaning: "todo", distractors: ["nada", "algo", "poco"] },
    { word: "抱いて", romaji: "daite", meaning: "abrazar", distractors: ["soltar", "empujar", "mirar"] },
    { word: "ここ", romaji: "koko", meaning: "aqui", distractors: ["alli", "alla", "ningun sitio"] },
    { word: "いる", romaji: "iru", meaning: "estar", distractors: ["ir", "venir", "dormir"] },
    { word: "光", romaji: "hikari", meaning: "luz", distractors: ["oscuridad", "sombra", "noche"] },
    { word: "そこ", romaji: "soko", meaning: "ahi", distractors: ["aqui", "alla", "ningun sitio"] },
    { word: "ある", romaji: "aru", meaning: "haber", distractors: ["no haber", "romper", "crear"] },
    { word: "ゆずれない", romaji: "yuzurenai", meaning: "no ceder", distractors: ["ceder", "abandonar", "olvidar"] },
    { word: "想い", romaji: "omoi", meaning: "sentimientos", distractors: ["olvido", "silencio", "duda"] },
    { word: "架けて", romaji: "kakete", meaning: "apostar", distractors: ["quitar", "guardar", "esconder"] },
    { word: "希望", romaji: "kibo", meaning: "esperanza", distractors: ["desesperacion", "miedo", "duda"] },
    { word: "果て", romaji: "hate", meaning: "extremo / confín", distractors: ["inicio", "centro", "mitad"] },
    { word: "僕", romaji: "boku", meaning: "yo", distractors: ["tu", "el", "nosotros"] },
    { word: "生きる", romaji: "ikiru", meaning: "vivir", distractors: ["morir", "dormir", "huir"] },
    { word: "夢", romaji: "yume", meaning: "sueno", distractors: ["pesadilla", "realidad", "recuerdo"] },
    { word: "つないだ", romaji: "tsunaida", meaning: "unio", distractors: ["rompio", "separo", "olvido"] },
    { word: "君", romaji: "kimi", meaning: "tu", distractors: ["yo", "el", "ellos"] },
    { word: "始まり", romaji: "hajimari", meaning: "comienzo", distractors: ["final", "medio", "pausa"] },
    { word: "いつか", romaji: "itsuka", meaning: "algun dia", distractors: ["nunca", "siempre", "ahora"] },
    { word: "僕ら", romaji: "bokura", meaning: "nosotros", distractors: ["vosotros", "ellos", "yo solo"] },
    { word: "手", romaji: "te", meaning: "mano", distractors: ["pie", "ojo", "cabeza"] },
    { word: "生み出す", romaji: "umidasu", meaning: "crear", distractors: ["destruir", "ocultar", "copiar"] },
    { word: "優しい", romaji: "yasashii", meaning: "amable", distractors: ["cruel", "frio", "duro"] },
    { word: "声", romaji: "koe", meaning: "voz", distractors: ["eco", "ruido", "silencio"] },
    { word: "きっと", romaji: "kitto", meaning: "seguro", distractors: ["quizas", "nunca", "apenas"] },
    { word: "世界", romaji: "sekai", meaning: "mundo", distractors: ["pais", "ciudad", "casa"] },
    { word: "変えられる", romaji: "kaerareru", meaning: "poder cambiar", distractors: ["romper", "congelar", "ignorar"] },
    { word: "誰も", romaji: "dare mo", meaning: "nadie", distractors: ["todos", "solo yo", "ellos"] },
    { word: "ひとりきり", romaji: "hitorikiri", meaning: "completamente solo", distractors: ["acompanado", "en grupo", "en pareja"] },
    { word: "起ち上がれ", romaji: "tachiagare", meaning: "levantate", distractors: ["sientate", "cae", "duerme"] },
    { word: "しない", romaji: "shinai", meaning: "no hacer", distractors: ["hacer", "intentar", "poder"] },
    { word: "たがいに", romaji: "tagai ni", meaning: "mutuamente", distractors: ["solo", "contra", "sin"] },
    { word: "伸ばして", romaji: "nobashite", meaning: "extender", distractors: ["retirar", "cerrar", "esconder"] },
    { word: "限界", romaji: "genkai", meaning: "limite", distractors: ["inicio", "centro", "infinito"] },
    { word: "越えた", romaji: "koeta", meaning: "supero", distractors: ["quedo", "cayo", "paro"] },
    { word: "明日", romaji: "ashita", meaning: "manana", distractors: ["ayer", "hoy", "noche"] },
    { word: "ぶつかりあって", romaji: "butsukariatte", meaning: "chocando", distractors: ["evitandose", "ignorandose", "huyendo"] },
    { word: "わかりあう", romaji: "wakariau", meaning: "entenderse", distractors: ["pelear", "ignorar", "odiar"] },
    { word: "つくりだす", romaji: "tsukuridasu", meaning: "crear", distractors: ["destruir", "copiar", "ocultar"] },
    { word: "諦めぬ", romaji: "akiramenu", meaning: "no rendirse", distractors: ["rendirse", "huir", "olvidar"] },
    { word: "悲しみ", romaji: "kanashimi", meaning: "tristeza", distractors: ["alegria", "ira", "miedo"] },
    { word: "怒り", romaji: "ikari", meaning: "ira", distractors: ["paz", "alegria", "amor"] }
  ],
  "op-tsubasa": [
    { word: "明け方", romaji: "akegata", meaning: "amanecer", distractors: ["atardecer", "noche", "mediodia"] },
    { word: "過ぎ", romaji: "sugi", meaning: "despues de", distractors: ["antes", "durante", "ahora"] },
    { word: "国道", romaji: "kokudo", meaning: "carretera nacional", distractors: ["calle", "camino", "autopista"] },
    { word: "細い", romaji: "hosoi", meaning: "estrecho", distractors: ["ancho", "grueso", "corto"] },
    { word: "抜け道", romaji: "nukemichi", meaning: "atajo", distractors: ["callejon sin salida", "autopista", "puente"] },
    { word: "君", romaji: "kimi", meaning: "tu", distractors: ["yo", "el", "ellos"] },
    { word: "呟く", romaji: "tsubuyaku", meaning: "murmurar", distractors: ["gritar", "cantar", "callar"] },
    { word: "恐い", romaji: "kowai", meaning: "aterrador", distractors: ["divertido", "bonito", "tranquilo"] },
    { word: "何も無い", romaji: "nanimo nai", meaning: "no hay nada", distractors: ["hay de todo", "sobra", "falta"] },
    { word: "見送る", romaji: "miokuru", meaning: "despedir", distractors: ["recibir", "llamar", "esperar"] },
    { word: "言葉", romaji: "kotoba", meaning: "palabra", distractors: ["silencio", "gesto", "ruido"] },
    { word: "涙", romaji: "namida", meaning: "lagrimas", distractors: ["sonrisa", "sangre", "sudor"] },
    { word: "流れた", romaji: "nagareta", meaning: "fluyeron", distractors: ["se secaron", "pararon", "subieron"] },
    { word: "つまらぬ", romaji: "tsumaranu", meaning: "trivial", distractors: ["importante", "interesante", "serio"] },
    { word: "話", romaji: "hanashi", meaning: "conversacion", distractors: ["pelea", "silencio", "carta"] },
    { word: "絶えず", romaji: "taezu", meaning: "sin cesar", distractors: ["a veces", "nunca", "raramente"] },
    { word: "散らかる", romaji: "chirakaru", meaning: "estar desordenado", distractors: ["ordenado", "limpio", "vacio"] },
    { word: "部屋", romaji: "heya", meaning: "habitacion", distractors: ["cocina", "calle", "jardin"] },
    { word: "笑いあえてた", romaji: "waraiaeteta", meaning: "podiamos reir juntos", distractors: ["llorabamos", "peleabamos", "callabamos"] },
    { word: "夢", romaji: "yume", meaning: "sueno", distractors: ["pesadilla", "realidad", "recuerdo"] },
    { word: "追う", romaji: "ou", meaning: "perseguir", distractors: ["huir", "evitar", "olvidar"] },
    { word: "恐れ", romaji: "osore", meaning: "miedo", distractors: ["valor", "alegria", "calma"] },
    { word: "無くて", romaji: "nakute", meaning: "sin", distractors: ["con", "teniendo", "siendo"] },
    { word: "生まれた", romaji: "umareta", meaning: "nacido", distractors: ["murio", "crecio", "llego"] },
    { word: "街", romaji: "machi", meaning: "ciudad", distractors: ["pais", "montana", "mar"] },
    { word: "サヨナラ", romaji: "sayonara", meaning: "adios", distractors: ["hola", "gracias", "perdon"] },
    { word: "決めた", romaji: "kimeta", meaning: "decidio", distractors: ["dudo", "olvido", "cambio"] },
    { word: "いつか", romaji: "itsuka", meaning: "algun dia", distractors: ["nunca", "siempre", "ahora"] },
    { word: "会いに来る", romaji: "ai ni kuru", meaning: "venir a ver", distractors: ["irse lejos", "llamar", "escribir"] },
    { word: "いつも", romaji: "itsumo", meaning: "siempre", distractors: ["nunca", "a veces", "raramente"] },
    { word: "忘れない", romaji: "wasurenai", meaning: "no olvidar", distractors: ["olvidar", "recordar mal", "ignorar"] },
    { word: "手を振る", romaji: "te wo furu", meaning: "agitar la mano", distractors: ["aplaudir", "senalar", "cerrar"] },
    { word: "瞳", romaji: "hitomi", meaning: "ojos / mirada", distractors: ["boca", "oreja", "mano"] },
    { word: "言えずに", romaji: "iezu ni", meaning: "sin poder decir", distractors: ["diciendo", "gritando", "escribiendo"] },
    { word: "ココロ", romaji: "kokoro", meaning: "corazon", distractors: ["cuerpo", "cabeza", "voz"] },
    { word: "中", romaji: "naka", meaning: "dentro", distractors: ["fuera", "arriba", "abajo"] },
    { word: "誓う", romaji: "chikau", meaning: "jurar", distractors: ["mentir", "dudar", "negar"] },
    { word: "旅立つ", romaji: "tabidatsu", meaning: "partir", distractors: ["llegar", "quedarse", "regresar"] },
    { word: "空", romaji: "sora", meaning: "cielo", distractors: ["tierra", "mar", "montana"] },
    { word: "出会い", romaji: "deai", meaning: "encuentro", distractors: ["despedida", "pelea", "olvido"] },
    { word: "別れ", romaji: "wakare", meaning: "separacion", distractors: ["encuentro", "union", "inicio"] },
    { word: "青春", romaji: "seishun", meaning: "juventud", distractors: ["vejez", "infancia", "muerte"] },
    { word: "日々", romaji: "hibi", meaning: "dias", distractors: ["noches", "anos", "segundos"] },
    { word: "全て", romaji: "subete", meaning: "todo", distractors: ["nada", "poco", "algo"] },
    { word: "描き", romaji: "egaki", meaning: "dibujar", distractors: ["borrar", "ocultar", "romper"] },
    { word: "互いに", romaji: "tagai ni", meaning: "mutuamente", distractors: ["solo", "contra", "sin"] },
    { word: "大きな", romaji: "okina", meaning: "grande", distractors: ["pequeno", "fino", "corto"] },
    { word: "花", romaji: "hana", meaning: "flor", distractors: ["arbol", "hoja", "fruta"] },
    { word: "綺麗な", romaji: "kirei na", meaning: "bonita", distractors: ["fea", "sucia", "rota"] },
    { word: "咲かせ", romaji: "sakase", meaning: "hacer florecer", distractors: ["marchitar", "cortar", "esconder"] },
    { word: "共に", romaji: "tomo ni", meaning: "juntos", distractors: ["solo", "separados", "despues"] },
    { word: "笑おう", romaji: "waraou", meaning: "riamos", distractors: ["lloremos", "pelemos", "calleemos"] },
    { word: "あの日", romaji: "ano hi", meaning: "aquel dia", distractors: ["hoy", "manana", "anoche"] },
    { word: "胸", romaji: "mune", meaning: "pecho", distractors: ["espalda", "mano", "cabeza"] },
    { word: "あて無く", romaji: "ate naku", meaning: "sin rumbo", distractors: ["con meta", "directo", "seguro"] },
    { word: "続く", romaji: "tsuzuku", meaning: "continuar", distractors: ["parar", "empezar", "terminar"] },
    { word: "道", romaji: "michi", meaning: "camino", distractors: ["casa", "puente", "muro"] },
    { word: "眠れぬ", romaji: "nemurenu", meaning: "sin poder dormir", distractors: ["dormilon", "despierto", "cansado"] },
    { word: "夜", romaji: "yoru", meaning: "noche", distractors: ["dia", "manana", "tarde"] },
    { word: "連なる", romaji: "tsuranaru", meaning: "encadenarse", distractors: ["separarse", "romper", "parar"] },
    { word: "叶いかけた", romaji: "kanai kaketa", meaning: "casi cumplido", distractors: ["imposible", "olvidado", "roto"] },
    { word: "紡ぎだした", romaji: "tsumugi dashita", meaning: "hilar / tejer", distractors: ["borrar", "romper", "ocultar"] },
    { word: "文字", romaji: "moji", meaning: "letras", distractors: ["numeros", "dibujos", "sonidos"] },
    { word: "狭間", romaji: "hazama", meaning: "espacio entre", distractors: ["centro", "borde", "cima"] },
    { word: "揺れる", romaji: "yureru", meaning: "temblar", distractors: ["quieto", "caer", "volar"] },
    { word: "気紛れ", romaji: "kimagure", meaning: "capricho", distractors: ["plan fijo", "deber", "costumbre"] },
    { word: "日替わり", romaji: "higawari", meaning: "que cambia cada dia", distractors: ["fijo", "semanal", "eterno"] },
    { word: "時計", romaji: "tokei", meaning: "reloj", distractors: ["calendario", "brujula", "mapa"] },
    { word: "針", romaji: "hari", meaning: "aguja", distractors: ["esfera", "cuerda", "pila"] },
    { word: "流れる", romaji: "nagareru", meaning: "fluir", distractors: ["detenerse", "subir", "congelar"] },
    { word: "雲", romaji: "kumo", meaning: "nube", distractors: ["sol", "estrella", "lluvia"] },
    { word: "明日", romaji: "asu", meaning: "manana", distractors: ["ayer", "hoy", "noche"] },
    { word: "誓えど", romaji: "chikaedo", meaning: "aunque jure", distractors: ["si niega", "cuando olvida", "sin prometer"] },
    { word: "置いてかれてる", romaji: "oite kareteru", meaning: "dejado atras", distractors: ["llevado", "protegido", "cercano"] },
    { word: "不安", romaji: "fuan", meaning: "inquietud", distractors: ["calma", "confianza", "alegria"] },
    { word: "よぎる", romaji: "yogiru", meaning: "pasar por la mente", distractors: ["quedarse", "olvidar", "ignorar"] },
    { word: "その度", romaji: "sono tabi", meaning: "cada vez", distractors: ["nunca", "una vez", "a veces"] },
    { word: "思い返して", romaji: "omoikaeshite", meaning: "recordar", distractors: ["olvidar", "ignorar", "borrar"] },
    { word: "集め", romaji: "atsume", meaning: "reunir", distractors: ["dispersar", "tirar", "ocultar"] },
    { word: "声枯らす", romaji: "koe karasu", meaning: "quedarse sin voz", distractors: ["cantar fuerte", "susurrar", "callar"] },
    { word: "今も", romaji: "ima mo", meaning: "aun ahora", distractors: ["nunca", "antes", "despues"] },
    { word: "信じている", romaji: "shinjite iru", meaning: "creer", distractors: ["dudar", "negar", "odiar"] },
    { word: "帰らぬ", romaji: "kaeranu", meaning: "que no vuelve", distractors: ["que vuelve", "eterno", "pasajero"] },
    { word: "儚き", romaji: "hakanaki", meaning: "efimero", distractors: ["eterno", "solido", "fuerte"] },
    { word: "蒼き", romaji: "aoki", meaning: "azul", distractors: ["rojo", "blanco", "negro"] },
    { word: "変わらぬ", romaji: "kawaranu", meaning: "que no cambia", distractors: ["cambiante", "nuevo", "viejo"] },
    { word: "映して", romaji: "utsushite", meaning: "reflejar", distractors: ["ocultar", "borrar", "romper"] },
    { word: "上手く", romaji: "umaku", meaning: "bien", distractors: ["mal", "torpe", "lento"] },
    { word: "飛べたら", romaji: "tobetara", meaning: "si pudiera volar", distractors: ["si cayera", "si corriera", "si nadara"] },
    { word: "高く", romaji: "takaku", meaning: "alto", distractors: ["bajo", "cerca", "lejos"] },
    { word: "ツバサ", romaji: "tsubasa", meaning: "alas", distractors: ["patas", "manos", "ojos"] },
    { word: "広げて", romaji: "hirogete", meaning: "extender", distractors: ["cerrar", "guardar", "doblar"] },
    { word: "秋風", romaji: "akikaze", meaning: "viento de otono", distractors: ["viento de primavera", "lluvia", "nieve"] },
    { word: "超えて", romaji: "koete", meaning: "superar", distractors: ["quedarse", "evitar", "parar"] },
    { word: "手にして", romaji: "te ni shite", meaning: "teniendo en la mano", distractors: ["perdiendo", "buscando", "esperando"] },
    { word: "会えたなら", romaji: "aeta nara", meaning: "si pudieramos encontrarnos", distractors: ["si nos separáramos", "si olvidáramos", "si huyéramos"] }
  ]
};

const EXTRA_DISTRACTORS = ["casa", "comida", "agua", "fuego", "libro", "amigo", "noche", "dia", "grande", "pequeno", "rapido", "lento", "feliz", "triste"];
